[theme]
base = "light"
primaryColor = "#B86A45"
backgroundColor = "#F7F2EC"
secondaryBackgroundColor = "#EFE7DE"
textColor = "#211D1A"
font = "sans-serif"

[theme.sidebar]
backgroundColor = "#171513"
secondaryBackgroundColor = "#24211E"
textColor = "#FFFDFC"
primaryColor = "#D9A94E"
font = "sans-serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"
